<?php

return [
    'JUPITER_BASE_URL' => env('JUPITER_BASE_URL'),
    'JUPITER_TOKEN' => env('JUPITER_TOKEN'),
    'VALORIZAR_BASE_URL' => env('VALORIZAR_BASE_URL'),
    'VALORIZAR_TOKEN' => env('VALORIZAR_TOKEN'),
];
